services:
  backend:
    user: 1000:1000
    image: oven/bun:latest
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      # Mongo
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}

      # Server
      BACKEND_PORT: ${BACKEND_PORT}

      # JWT
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ACCESS_TOKEN_EXPIRATION: ${ACCESS_TOKEN_EXPIRATION}
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION}

      # S3
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
    command: sh -c "bun i && bun start"

  mongo:
    user: 1000:1000
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_DB: ${MONGO_DB}

  minio:
    user: 1000:1000
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    volumes:
      - ./minio/data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
  minio-console:
    image: minio/mc:latest
    container_name: minio-console
    restart: on-failure
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY};
      while ! mc ls minio/${S3_BUCKET}; do
        mc mb minio/${S3_BUCKET};
        sleep 1;
      done;
      mc anonymous set download minio/${S3_BUCKET};
      "
